export const Api = [
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "574262",
        name: "California Burrito",
        uuid: "900d0f7e-9e6b-450b-a575-1a711504d0bf",
        city: "10459",
        area: "Sector 98",
        totalRatingsString: "500+ ratings",
        cloudinaryImageId: "tg61d1oklma3204j3gqd",
        cuisines: [
          "Mexican",
          "American",
          "Salads",
          "Continental",
          "Keto",
          "Healthy Food",
        ],
      },
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "594707",
        name: "The Momo Co.",
        uuid: "e5e2560e-6941-472b-9373-a3f6d4cea2bf",
        city: "10459",
        area: "Sector 110",
        totalRatingsString: "20+ ratings",
        cloudinaryImageId: "dneq0actq61piimsxxqn",
        cuisines: ["Chinese", "Asian", "Tibetan", "Desserts"],
      },
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "22167",
        name: "The Cake Expert's",
        uuid: "e2b25a81-a2b2-4920-b229-c26261ab9744",
        city: "10459",
        area: "Sector 110",
        totalRatingsString: "20+ ratings",
        cloudinaryImageId: "hmocpptkhu7vavaqwsgr",
        cuisines: ["Bakery", "Fast Food", "North Indian"],
      },
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "90872",
        name: "Burger King",
        uuid: "e2e3f61a-20a5-4a95-85d6-d69da7fee3b6",
        city: "10459",
        area: "Sector 74",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "yaxffotup5nzfti0hoq1",
        cuisines: ["Burgers", "American"],
      },
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "594715",
        name: "Big Bowl (Big Bowl Company)",
        uuid: "c00b38fd-d721-4b07-8584-a2fa88307add",
        city: "10459",
        area: "Sector 110",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "nzmodhempcy9rgfi9mxw",
        cuisines: ["North Indian", "Chinese", "Tibetan", "Desserts"],
      },
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "413001",
        name: "Biryani Blues",
        uuid: "3e9f6144-a996-4381-9179-ee335449c404",
        city: "10459",
        area: "Sector 110",
        totalRatingsString: "500+ ratings",
        cloudinaryImageId: "czrcorqk8xoyxrzflbr8",
        cuisines: [
          "Biryani",
          "Hyderabadi",
          "Lucknowi",
          "Kebabs",
          "Desserts",
          "Beverages",
        ],
      },
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "594685",
        name: "Chinese Wok",
        uuid: "b489bf51-db8c-4696-852b-af0ada970413",
        city: "10459",
        area: "Sector 110",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "ug092obm9ihwupmmvun8",
        cuisines: ["Chinese", "Asian", "Tibetan", "Desserts"],
      },
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "318412",
        name: "Nirula's",
        uuid: "a8af001e-6b00-454c-a086-367dcfd7229c",
        city: "10459",
        area: "Sector 93",
        totalRatingsString: "20+ ratings",
        cloudinaryImageId: "gqbtllvwjy3mxvrb60ly",
        cuisines: [
          "Desserts",
          "Ice Cream",
          "Beverages",
          "Ice Cream Cakes",
          "Juices",
        ],
      },
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "114211",
        name: "Folks n knives",
        uuid: "44c38dd7-ada9-4ab0-8328-3ba193adb7b0",
        city: "10459",
        area: "Sector 72",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "wbuf4znrbuxwzlmj3gii",
        cuisines: ["Chinese", "North Indian"],
      },
    },
  ];
  
  export const ImgLink =  "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";